# Generated by Django 5.0.1 on 2024-02-26 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0002_delete_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=200)),
                ('id_type', models.CharField(max_length=100)),
                ('id_number', models.CharField(max_length=50)),
            ],
        ),
    ]
