# Generated by Django 5.0.1 on 2024-03-07 04:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_te', models.DateTimeField(auto_now_add=True)),
                ('updated_te', models.DateTimeField(auto_now=True)),
                ('trip_start', models.DateTimeField()),
                ('trip_end', models.DateTimeField()),
                ('pickup_point', models.CharField(max_length=45)),
                ('drop_point', models.CharField(max_length=45)),
                ('no_of_day', models.IntegerField()),
                ('base_cost', models.FloatField()),
                ('transportation_cost', models.FloatField()),
                ('tax', models.FloatField()),
                ('total_amount', models.FloatField()),
                ('payment_method', models.CharField(max_length=10)),
                ('payment_date', models.DateTimeField()),
                ('booking_status', models.CharField(max_length=10)),
                ('refund_amount', models.FloatField()),
                ('refund_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_te', models.DateTimeField(auto_now_add=True)),
                ('updated_te', models.DateTimeField(auto_now=True)),
                ('trip_start', models.DateTimeField()),
                ('trip_end', models.DateTimeField()),
                ('pickup_point', models.CharField(max_length=45)),
                ('drop_point', models.CharField(max_length=45)),
                ('no_of_day', models.IntegerField()),
                ('base_cost', models.FloatField()),
                ('transportation_cost', models.FloatField()),
                ('tax', models.FloatField()),
                ('total_amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CMSPages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_name', models.CharField(max_length=55)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=255)),
                ('idprooftype', models.CharField(max_length=20)),
                ('idproofnumber', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transportation_type', models.CharField(max_length=10)),
                ('transportation_details', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_place', models.CharField(max_length=45)),
                ('end_place', models.CharField(max_length=45)),
                ('no_of_day', models.IntegerField()),
                ('category', models.CharField(max_length=45)),
                ('city', models.CharField(max_length=45)),
                ('cms_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.cmspages')),
                ('transportation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.transportation')),
            ],
        ),
        migrations.CreateModel(
            name='TripDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('cost', models.FloatField()),
                ('transportation_cost', models.FloatField()),
                ('tax', models.FloatField()),
                ('transportation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.transportation')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=255)),
                ('userrole', models.CharField(max_length=10)),
                ('idprooftype', models.CharField(max_length=20)),
                ('idproofnumber', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=45)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='users',
        ),
        migrations.AddField(
            model_name='members',
            name='transportation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.transportation'),
        ),
        migrations.AddField(
            model_name='cart',
            name='transportation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.transportation'),
        ),
        migrations.AddField(
            model_name='booking',
            name='transportation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.transportation'),
        ),
        migrations.AddField(
            model_name='members',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.trip'),
        ),
        migrations.AddField(
            model_name='cart',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.trip'),
        ),
        migrations.AddField(
            model_name='booking',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.trip'),
        ),
        migrations.AddField(
            model_name='trip',
            name='trip_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.tripdetail'),
        ),
        migrations.AddField(
            model_name='members',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.userprofile'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.userprofile'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.userprofile'),
        ),
    ]
