# Generated by Django 5.0.1 on 2024-03-07 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_booking_cart_cmspages_members_transportation_trip_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='transportation',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='trip',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='cms_page',
        ),
        migrations.RemoveField(
            model_name='members',
            name='transportation',
        ),
        migrations.RemoveField(
            model_name='members',
            name='trip',
        ),
        migrations.RemoveField(
            model_name='members',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tripdetail',
            name='transportation',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='transportation',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='trip_detail',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CMSPages',
        ),
        migrations.DeleteModel(
            name='Members',
        ),
        migrations.DeleteModel(
            name='Transportation',
        ),
        migrations.DeleteModel(
            name='Trip',
        ),
        migrations.DeleteModel(
            name='TripDetail',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
