# Generated by Django 5.0.1 on 2024-03-07 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
