# Generated by Django 5.0.1 on 2024-03-08 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0007_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CmsPage',
            fields=[
                ('cms_page_id', models.AutoField(primary_key=True, serialize=False)),
                ('page_title', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('transportation_id', models.AutoField(primary_key=True, serialize=False)),
                ('transportation_type', models.CharField(max_length=10)),
                ('transportation_details', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=255, null=True)),
                ('lname', models.CharField(max_length=255, null=True)),
                ('username', models.CharField(max_length=55, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=255, null=True)),
                ('dob', models.DateField(null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('userrole', models.CharField(max_length=10, null=True)),
                ('idprooftype', models.CharField(max_length=20, null=True)),
                ('idproofnumber', models.CharField(max_length=20, null=True)),
                ('password', models.CharField(max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TripDetail',
            fields=[
                ('trip_detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('cost', models.FloatField(null=True)),
                ('transportation_cost', models.FloatField(null=True)),
                ('tax', models.FloatField(null=True)),
                ('transportation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.transportation')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_place', models.CharField(max_length=45)),
                ('end_place', models.CharField(max_length=45)),
                ('no_of_day', models.IntegerField(null=True)),
                ('category', models.CharField(max_length=45)),
                ('city', models.CharField(max_length=45)),
                ('cms_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.cmspage')),
                ('transportation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.transportation')),
                ('trip_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.tripdetail')),
            ],
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('member_id', models.AutoField(primary_key=True, serialize=False)),
                ('m_name', models.CharField(max_length=55)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=255, null=True)),
                ('dob', models.DateField(null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('idprooftype', models.CharField(max_length=20, null=True)),
                ('idproofnumber', models.CharField(max_length=20, null=True)),
                ('transportation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.transportation')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.users')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_te', models.DateTimeField(auto_now_add=True)),
                ('updated_te', models.DateTimeField(auto_now=True)),
                ('trip_start', models.DateTimeField(null=True)),
                ('trip_end', models.DateTimeField(null=True)),
                ('pickup_point', models.CharField(max_length=45)),
                ('drop_point', models.CharField(max_length=45)),
                ('no_of_day', models.IntegerField(null=True)),
                ('base_cost', models.FloatField(null=True)),
                ('transportation_cost', models.FloatField(null=True)),
                ('tax', models.FloatField(null=True)),
                ('total_amount', models.FloatField(null=True)),
                ('transportation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.transportation')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.users')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_te', models.DateTimeField(auto_now_add=True)),
                ('updated_te', models.DateTimeField(auto_now=True)),
                ('trip_start', models.DateTimeField(null=True)),
                ('trip_end', models.DateTimeField(null=True)),
                ('pickup_point', models.CharField(max_length=45)),
                ('drop_point', models.CharField(max_length=45)),
                ('no_of_day', models.IntegerField(null=True)),
                ('base_cost', models.FloatField(null=True)),
                ('transportation_cost', models.FloatField(null=True)),
                ('tax', models.FloatField(null=True)),
                ('total_amount', models.FloatField(null=True)),
                ('payment_method', models.CharField(max_length=10)),
                ('payment_date', models.DateTimeField(null=True)),
                ('booking_status', models.CharField(max_length=10)),
                ('refund_amount', models.FloatField(null=True)),
                ('refund_date', models.DateTimeField(null=True)),
                ('transportation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.transportation')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.users')),
            ],
        ),
    ]
