# Generated by Django 5.0.1 on 2024-03-11 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_userdetailstab_alter_booking_user_alter_cart_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
