# Generated by Django 5.0.1 on 2024-03-12 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_delete_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='trip_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
