# Generated by Django 5.0.1 on 2024-03-12 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_trip_trip_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='trip_name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('package_id', models.AutoField(primary_key=True, serialize=False)),
                ('package_name', models.CharField(max_length=100)),
                ('no_of_day', models.IntegerField(null=True)),
                ('category', models.CharField(max_length=45)),
                ('city', models.CharField(max_length=45)),
                ('total_amt', models.FloatField(null=True)),
                ('description', models.TextField()),
                ('cms_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.cmspage')),
                ('transportation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.transportation')),
                ('trip_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.tripdetail')),
            ],
        ),
    ]
