# Generated by Django 5.0.1 on 2024-03-14 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_remove_trip_trip_name_delete_packages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='transportation',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='trip',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='cms_page',
        ),
        migrations.RemoveField(
            model_name='members',
            name='transportation',
        ),
        migrations.RemoveField(
            model_name='members',
            name='trip',
        ),
        migrations.RemoveField(
            model_name='members',
            name='user',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='transportation',
        ),
        migrations.RemoveField(
            model_name='tripdetail',
            name='transportation',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='trip_detail',
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('alternative_phone', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('date_of_birth', models.DateField()),
                ('blood_group', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=255)),
                ('id_type', models.CharField(max_length=20)),
                ('id_image', models.ImageField(upload_to='id_images/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CmsPage',
        ),
        migrations.DeleteModel(
            name='Members',
        ),
        migrations.DeleteModel(
            name='UserDetailsTab',
        ),
        migrations.DeleteModel(
            name='Transportation',
        ),
        migrations.DeleteModel(
            name='Trip',
        ),
        migrations.DeleteModel(
            name='TripDetail',
        ),
    ]
