# Generated by Django 5.0.1 on 2024-03-14 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_cmspages_transportation_trip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('city', models.CharField(max_length=45)),
                ('image', models.ImageField(upload_to='package_images/')),
                ('description', models.CharField(max_length=255)),
                ('start_place', models.CharField(max_length=45)),
                ('end_place', models.CharField(max_length=45)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('duration_days', models.IntegerField()),
                ('category', models.CharField(max_length=45)),
                ('cost', models.CharField(max_length=100)),
                ('cms_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.cmspages')),
                ('transportation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.transportation')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('date_of_birth', models.DateField()),
                ('blood_group', models.CharField(max_length=10)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='booking.trip')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='booking.package')),
            ],
        ),
    ]
