# Generated by Django 5.0.1 on 2024-03-14 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0016_package_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_members', models.CharField(max_length=45)),
                ('payment_method', models.CharField(max_length=20)),
                ('booking_status', models.CharField(max_length=20)),
                ('additional_booking_details', models.TextField(blank=True, null=True)),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.package')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.trip')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_members', models.CharField(max_length=45)),
                ('payment_method', models.CharField(max_length=20)),
                ('booking_status', models.CharField(max_length=20)),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.package')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.trip')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.userprofile')),
            ],
        ),
    ]
