# Generated by Django 5.0.1 on 2024-03-14 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_booking_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='id_type',
            field=models.CharField(choices=[('passport', 'Passport'), ('driving_license', 'Driving License'), ('national_id', 'National ID'), ('other', 'Other')], max_length=20),
        ),
    ]
