# Generated by Django 5.0.1 on 2024-03-14 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0018_alter_userprofile_id_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DestinationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=45)),
            ],
        ),
        migrations.RenameField(
            model_name='transportation',
            old_name='type',
            new_name='t_type',
        ),
        migrations.AlterField(
            model_name='package',
            name='image',
            field=models.ImageField(upload_to='admin_use'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='image',
            field=models.ImageField(upload_to='admin_use'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id_image',
            field=models.ImageField(upload_to='user_use'),
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('des_name', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='admin_use')),
                ('des_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.destinationcategory')),
            ],
        ),
    ]
