# Generated by Django 5.0.1 on 2024-03-14 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0019_destinationcategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='trip',
        ),
        migrations.RemoveField(
            model_name='member',
            name='trip',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='trip',
        ),
        migrations.DeleteModel(
            name='Trip',
        ),
    ]
