# Generated by Django 5.0.1 on 2024-03-14 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0020_remove_booking_trip_remove_member_trip_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='name',
            new_name='p_name',
        ),
    ]
