# Generated by Django 5.0.1 on 2024-03-15 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0021_rename_name_package_p_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='destinations',
            field=models.ManyToManyField(to='booking.destination'),
        ),
    ]
