# Generated by Django 5.0.1 on 2024-03-15 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0022_booking_destinations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='destinations',
        ),
    ]
