# Generated by Django 5.0.1 on 2024-03-15 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0023_remove_booking_destinations'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='destinations',
            field=models.ManyToManyField(to='booking.destination'),
        ),
        migrations.CreateModel(
            name='TripRoot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_place', models.CharField(max_length=45)),
                ('end_place', models.CharField(max_length=45)),
                ('pickup_point', models.CharField(max_length=45)),
                ('drop_point', models.CharField(max_length=45)),
                ('cost', models.CharField(max_length=100)),
                ('gst_charge', models.CharField(max_length=100)),
                ('cms_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.cmspages')),
                ('transportation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.transportation')),
            ],
        ),
    ]
