# Generated by Django 5.0.1 on 2024-03-19 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstType', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default='ABCD', max_length=50),
            preserve_default=False,
        ),
    ]
